name: Feature Request
description: Suggest a new feature
title: "[FEATURE] "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please describe your feature request below.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Clear description of the feature you'd like
      placeholder: "Describe the feature..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why do you need this feature?
      placeholder: "What problem does this solve?"
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Possible Implementation
      description: How could this be implemented?
      placeholder: "Any ideas on how to implement this?"

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative approaches?
      placeholder: "Are there any alternatives?"

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
